/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiNonceRouteImport } from './routes/api/nonce'
import { Route as ApiCandlesRouteImport } from './routes/api/candles'
import { Route as ApiBalanceRouteImport } from './routes/api/balance'
import { Route as ApiJudgmentStreamRouteImport } from './routes/api/judgment.stream'
import { Route as ApiJudgmentHistoryRouteImport } from './routes/api/judgment.history'
import { Route as AdminJudgmentTickRouteImport } from './routes/admin/judgment.tick'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNonceRoute = ApiNonceRouteImport.update({
  id: '/api/nonce',
  path: '/api/nonce',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCandlesRoute = ApiCandlesRouteImport.update({
  id: '/api/candles',
  path: '/api/candles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBalanceRoute = ApiBalanceRouteImport.update({
  id: '/api/balance',
  path: '/api/balance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJudgmentStreamRoute = ApiJudgmentStreamRouteImport.update({
  id: '/api/judgment/stream',
  path: '/api/judgment/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJudgmentHistoryRoute = ApiJudgmentHistoryRouteImport.update({
  id: '/api/judgment/history',
  path: '/api/judgment/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJudgmentTickRoute = AdminJudgmentTickRouteImport.update({
  id: '/admin/judgment/tick',
  path: '/admin/judgment/tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/api/balance': typeof ApiBalanceRoute
  '/api/candles': typeof ApiCandlesRoute
  '/api/nonce': typeof ApiNonceRoute
  '/admin/judgment/tick': typeof AdminJudgmentTickRoute
  '/api/judgment/history': typeof ApiJudgmentHistoryRoute
  '/api/judgment/stream': typeof ApiJudgmentStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/api/balance': typeof ApiBalanceRoute
  '/api/candles': typeof ApiCandlesRoute
  '/api/nonce': typeof ApiNonceRoute
  '/admin/judgment/tick': typeof AdminJudgmentTickRoute
  '/api/judgment/history': typeof ApiJudgmentHistoryRoute
  '/api/judgment/stream': typeof ApiJudgmentStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/api/balance': typeof ApiBalanceRoute
  '/api/candles': typeof ApiCandlesRoute
  '/api/nonce': typeof ApiNonceRoute
  '/admin/judgment/tick': typeof AdminJudgmentTickRoute
  '/api/judgment/history': typeof ApiJudgmentHistoryRoute
  '/api/judgment/stream': typeof ApiJudgmentStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/dashboard'
    | '/login'
    | '/logout'
    | '/api/balance'
    | '/api/candles'
    | '/api/nonce'
    | '/admin/judgment/tick'
    | '/api/judgment/history'
    | '/api/judgment/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent'
    | '/dashboard'
    | '/login'
    | '/logout'
    | '/api/balance'
    | '/api/candles'
    | '/api/nonce'
    | '/admin/judgment/tick'
    | '/api/judgment/history'
    | '/api/judgment/stream'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/dashboard'
    | '/login'
    | '/logout'
    | '/api/balance'
    | '/api/candles'
    | '/api/nonce'
    | '/admin/judgment/tick'
    | '/api/judgment/history'
    | '/api/judgment/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  ApiBalanceRoute: typeof ApiBalanceRoute
  ApiCandlesRoute: typeof ApiCandlesRoute
  ApiNonceRoute: typeof ApiNonceRoute
  AdminJudgmentTickRoute: typeof AdminJudgmentTickRoute
  ApiJudgmentHistoryRoute: typeof ApiJudgmentHistoryRoute
  ApiJudgmentStreamRoute: typeof ApiJudgmentStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nonce': {
      id: '/api/nonce'
      path: '/api/nonce'
      fullPath: '/api/nonce'
      preLoaderRoute: typeof ApiNonceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/candles': {
      id: '/api/candles'
      path: '/api/candles'
      fullPath: '/api/candles'
      preLoaderRoute: typeof ApiCandlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/balance': {
      id: '/api/balance'
      path: '/api/balance'
      fullPath: '/api/balance'
      preLoaderRoute: typeof ApiBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/judgment/stream': {
      id: '/api/judgment/stream'
      path: '/api/judgment/stream'
      fullPath: '/api/judgment/stream'
      preLoaderRoute: typeof ApiJudgmentStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/judgment/history': {
      id: '/api/judgment/history'
      path: '/api/judgment/history'
      fullPath: '/api/judgment/history'
      preLoaderRoute: typeof ApiJudgmentHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/judgment/tick': {
      id: '/admin/judgment/tick'
      path: '/admin/judgment/tick'
      fullPath: '/admin/judgment/tick'
      preLoaderRoute: typeof AdminJudgmentTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  ApiBalanceRoute: ApiBalanceRoute,
  ApiCandlesRoute: ApiCandlesRoute,
  ApiNonceRoute: ApiNonceRoute,
  AdminJudgmentTickRoute: AdminJudgmentTickRoute,
  ApiJudgmentHistoryRoute: ApiJudgmentHistoryRoute,
  ApiJudgmentStreamRoute: ApiJudgmentStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
