/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LiveAssetRouteImport } from './routes/live.$asset'
import { Route as ApiNonceRouteImport } from './routes/api/nonce'
import { Route as ApiDecisionsRouteImport } from './routes/api/decisions'
import { Route as ApiCandlesRouteImport } from './routes/api/candles'
import { Route as ApiBalanceRouteImport } from './routes/api/balance'
import { Route as AdminShadowRouteImport } from './routes/admin/shadow'
import { Route as AdminBacktestRouteImport } from './routes/admin/backtest'
import { Route as ApiJudgmentStreamRouteImport } from './routes/api/judgment.stream'
import { Route as AdminDecisionTickRouteImport } from './routes/admin/decision.tick'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveAssetRoute = LiveAssetRouteImport.update({
  id: '/live/$asset',
  path: '/live/$asset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNonceRoute = ApiNonceRouteImport.update({
  id: '/api/nonce',
  path: '/api/nonce',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDecisionsRoute = ApiDecisionsRouteImport.update({
  id: '/api/decisions',
  path: '/api/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCandlesRoute = ApiCandlesRouteImport.update({
  id: '/api/candles',
  path: '/api/candles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBalanceRoute = ApiBalanceRouteImport.update({
  id: '/api/balance',
  path: '/api/balance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShadowRoute = AdminShadowRouteImport.update({
  id: '/admin/shadow',
  path: '/admin/shadow',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBacktestRoute = AdminBacktestRouteImport.update({
  id: '/admin/backtest',
  path: '/admin/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJudgmentStreamRoute = ApiJudgmentStreamRouteImport.update({
  id: '/api/judgment/stream',
  path: '/api/judgment/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDecisionTickRoute = AdminDecisionTickRouteImport.update({
  id: '/admin/decision/tick',
  path: '/admin/decision/tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/admin/backtest': typeof AdminBacktestRoute
  '/admin/shadow': typeof AdminShadowRoute
  '/api/balance': typeof ApiBalanceRoute
  '/api/candles': typeof ApiCandlesRoute
  '/api/decisions': typeof ApiDecisionsRoute
  '/api/nonce': typeof ApiNonceRoute
  '/live/$asset': typeof LiveAssetRoute
  '/admin/decision/tick': typeof AdminDecisionTickRoute
  '/api/judgment/stream': typeof ApiJudgmentStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/admin/backtest': typeof AdminBacktestRoute
  '/admin/shadow': typeof AdminShadowRoute
  '/api/balance': typeof ApiBalanceRoute
  '/api/candles': typeof ApiCandlesRoute
  '/api/decisions': typeof ApiDecisionsRoute
  '/api/nonce': typeof ApiNonceRoute
  '/live/$asset': typeof LiveAssetRoute
  '/admin/decision/tick': typeof AdminDecisionTickRoute
  '/api/judgment/stream': typeof ApiJudgmentStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/admin/backtest': typeof AdminBacktestRoute
  '/admin/shadow': typeof AdminShadowRoute
  '/api/balance': typeof ApiBalanceRoute
  '/api/candles': typeof ApiCandlesRoute
  '/api/decisions': typeof ApiDecisionsRoute
  '/api/nonce': typeof ApiNonceRoute
  '/live/$asset': typeof LiveAssetRoute
  '/admin/decision/tick': typeof AdminDecisionTickRoute
  '/api/judgment/stream': typeof ApiJudgmentStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/dashboard'
    | '/login'
    | '/logout'
    | '/admin/backtest'
    | '/admin/shadow'
    | '/api/balance'
    | '/api/candles'
    | '/api/decisions'
    | '/api/nonce'
    | '/live/$asset'
    | '/admin/decision/tick'
    | '/api/judgment/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent'
    | '/dashboard'
    | '/login'
    | '/logout'
    | '/admin/backtest'
    | '/admin/shadow'
    | '/api/balance'
    | '/api/candles'
    | '/api/decisions'
    | '/api/nonce'
    | '/live/$asset'
    | '/admin/decision/tick'
    | '/api/judgment/stream'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/dashboard'
    | '/login'
    | '/logout'
    | '/admin/backtest'
    | '/admin/shadow'
    | '/api/balance'
    | '/api/candles'
    | '/api/decisions'
    | '/api/nonce'
    | '/live/$asset'
    | '/admin/decision/tick'
    | '/api/judgment/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  AdminBacktestRoute: typeof AdminBacktestRoute
  AdminShadowRoute: typeof AdminShadowRoute
  ApiBalanceRoute: typeof ApiBalanceRoute
  ApiCandlesRoute: typeof ApiCandlesRoute
  ApiDecisionsRoute: typeof ApiDecisionsRoute
  ApiNonceRoute: typeof ApiNonceRoute
  LiveAssetRoute: typeof LiveAssetRoute
  AdminDecisionTickRoute: typeof AdminDecisionTickRoute
  ApiJudgmentStreamRoute: typeof ApiJudgmentStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$asset': {
      id: '/live/$asset'
      path: '/live/$asset'
      fullPath: '/live/$asset'
      preLoaderRoute: typeof LiveAssetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nonce': {
      id: '/api/nonce'
      path: '/api/nonce'
      fullPath: '/api/nonce'
      preLoaderRoute: typeof ApiNonceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/decisions': {
      id: '/api/decisions'
      path: '/api/decisions'
      fullPath: '/api/decisions'
      preLoaderRoute: typeof ApiDecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/candles': {
      id: '/api/candles'
      path: '/api/candles'
      fullPath: '/api/candles'
      preLoaderRoute: typeof ApiCandlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/balance': {
      id: '/api/balance'
      path: '/api/balance'
      fullPath: '/api/balance'
      preLoaderRoute: typeof ApiBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/shadow': {
      id: '/admin/shadow'
      path: '/admin/shadow'
      fullPath: '/admin/shadow'
      preLoaderRoute: typeof AdminShadowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/backtest': {
      id: '/admin/backtest'
      path: '/admin/backtest'
      fullPath: '/admin/backtest'
      preLoaderRoute: typeof AdminBacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/judgment/stream': {
      id: '/api/judgment/stream'
      path: '/api/judgment/stream'
      fullPath: '/api/judgment/stream'
      preLoaderRoute: typeof ApiJudgmentStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/decision/tick': {
      id: '/admin/decision/tick'
      path: '/admin/decision/tick'
      fullPath: '/admin/decision/tick'
      preLoaderRoute: typeof AdminDecisionTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  AdminBacktestRoute: AdminBacktestRoute,
  AdminShadowRoute: AdminShadowRoute,
  ApiBalanceRoute: ApiBalanceRoute,
  ApiCandlesRoute: ApiCandlesRoute,
  ApiDecisionsRoute: ApiDecisionsRoute,
  ApiNonceRoute: ApiNonceRoute,
  LiveAssetRoute: LiveAssetRoute,
  AdminDecisionTickRoute: AdminDecisionTickRoute,
  ApiJudgmentStreamRoute: ApiJudgmentStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
