/**
 * Maizzle post-build step: reads the compiled HTML from
 * emails/build_production/src/templates and writes
 * lib/email/compiled-templates.ts so the runtime send helpers can
 * import the strings directly instead of reading files at request
 * time. Avoids Vercel output-tracing surprises and keeps cold-start
 * cheap (no fs roundtrip per email send).
 *
 * Run as part of `bun run emails:build`. The generated TS file is
 * committed.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const srcDir = join(here, "build_production", "src", "templates");
const outPath = join(here, "..", "lib", "email", "compiled-templates.ts");

const templates = ["waitlist-confirmation", "beta-invite"];
const blocks = templates.map((name) => {
  const html = readFileSync(join(srcDir, `${name}.html`), "utf8");
  const camel = name.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
  return `export const ${camel} = ${JSON.stringify(html)};`;
});

const header = `// AUTO-GENERATED by emails/bake.mjs. Edit templates under emails/src/ and\n// re-run \`bun run emails:build\` to regenerate. Do not edit by hand.\n`;
writeFileSync(outPath, `${header}\n${blocks.join("\n\n")}\n`);
console.log(`Wrote ${outPath} (${blocks.length} templates)`);
