import type { ReaderHypothesis } from "./types";

export const defaultReaderHypotheses: ReaderHypothesis[] = [
  {
    id: "vp-active-long-first-reaction-nonnegative",
    label: "VP active long, first reaction non-negative",
    description: "Mixed VP pullback candidate family with tight invalidation, active tape, long side, and no adverse first reaction.",
    kind: "mixed-reader",
    filters: {
      side: "long",
      minInvalidationBps: 2,
      maxInvalidationBps: 5,
      minTradeCount: 500,
      maxTradeCount: 1000,
      maxAbsResultR: 100,
    },
    confirmation: {
      type: "first-reaction",
      thresholdR: 0,
    },
  },
  {
    id: "vp-trend-down-active-price-follow-025",
    label: "VP trend-down active tape, 0.25R price follow",
    description: "Adverse-reader trend-down pullback family with tight invalidation, active tape, and 0.25R price-follow confirmation.",
    kind: "adverse-reader",
    filters: {
      regime: "trend-down",
      minInvalidationBps: 2,
      maxInvalidationBps: 5,
      minTradeCount: 500,
      maxTradeCount: 1000,
      maxAbsResultR: 100,
    },
    confirmation: {
      type: "max-favorable",
      thresholdR: 0.25,
    },
  },
  {
    id: "vp-confirmed-absorption-trend-down-price-follow-025",
    label: "VP confirmed absorption trend-down, 0.25R price follow",
    description: "Concentrated adverse-reader absorption setup with trend-down regime and 0.25R price-follow confirmation.",
    kind: "adverse-reader",
    filters: {
      regime: "trend-down",
      event: "confirmed-absorption",
      minInvalidationBps: 2,
      maxInvalidationBps: 5,
      minTradeCount: 500,
      maxTradeCount: 1000,
      maxAbsResultR: 100,
    },
    confirmation: {
      type: "max-favorable",
      thresholdR: 0.25,
    },
  },
  {
    id: "trend-pullback-continuation-price-follow-025",
    label: "Trend-pullback continuation, 0.25R price follow",
    description: "Trend-following continuation family with tight invalidation and 0.25R price-follow confirmation.",
    kind: "trend-following",
    filters: {
      family: "trend-continuation",
      minInvalidationBps: 2,
      maxInvalidationBps: 5,
      minTradeCount: 0,
      maxTradeCount: 1000,
      maxAbsResultR: 100,
    },
    confirmation: {
      type: "max-favorable",
      thresholdR: 0.25,
    },
  },
  {
    id: "trend-pullback-long-thin-immediate",
    label: "Trend-pullback long thin immediate baseline",
    description: "Long trend-pullback baseline with tight invalidation and thin orderflow participation.",
    kind: "trend-following",
    filters: {
      side: "long",
      minInvalidationBps: 2,
      maxInvalidationBps: 5,
      minTradeCount: 0,
      maxTradeCount: 250,
      maxAbsResultR: 100,
    },
    confirmation: {
      type: "none",
      thresholdR: 0,
    },
  },

  // Tighter loss filters: block trades when VP is bearish
  {
    id: "long-no-vp-bear-poc-stable-value-stable",
    label: "Long only when POC stable + value stable",
    description: "Long trades filtered to only allow when POC is stable and value is stable - blocks VP bearish setups.",
    kind: "mixed-reader",
    filters: {
      side: "long",
      vpPoc: "poc-stable",
      vpValue: "value-stable",
      minInvalidationBps: 2,
      maxInvalidationBps: 5,
      minTradeCount: 250,
      maxTradeCount: 1000,
      maxAbsResultR: 100,
    },
    confirmation: {
      type: "max-favorable",
      thresholdR: 0.25,
    },
  },
  {
    id: "long-no-vp-bear-poc-migrate-up",
    label: "Long only when POC migrating up",
    description: "Long trades filtered to only allow when POC is migrating up - confirms bullish VP.",
    kind: "trend-following",
    filters: {
      side: "long",
      vpPoc: "poc-migrating-up",
      minInvalidationBps: 2,
      maxInvalidationBps: 5,
      minTradeCount: 250,
      maxTradeCount: 1000,
      maxAbsResultR: 100,
    },
    confirmation: {
      type: "max-favorable",
      thresholdR: 0.25,
    },
  },
  {
    id: "short-no-vp-bull-poc-stable-value-stable",
    label: "Short only when POC stable + value stable",
    description: "Short trades filtered to only allow when POC is stable and value is stable - blocks VP bullish setups.",
    kind: "mixed-reader",
    filters: {
      side: "short",
      vpPoc: "poc-stable",
      vpValue: "value-stable",
      minInvalidationBps: 2,
      maxInvalidationBps: 5,
      minTradeCount: 250,
      maxTradeCount: 1000,
      maxAbsResultR: 100,
    },
    confirmation: {
      type: "max-favorable",
      thresholdR: 0.25,
    },
  },
  {
    id: "short-no-vp-bull-poc-migrate-down",
    label: "Short only when POC migrating down",
    description: "Short trades filtered to only allow when POC is migrating down - confirms bearish VP.",
    kind: "adverse-reader",
    filters: {
      side: "short",
      vpPoc: "poc-migrating-down",
      minInvalidationBps: 2,
      maxInvalidationBps: 5,
      minTradeCount: 250,
      maxTradeCount: 1000,
      maxAbsResultR: 100,
    },
    confirmation: {
      type: "max-favorable",
      thresholdR: 0.25,
    },
  },
  {
    id: "long-absorption-poc-migrate-up",
    label: "Long absorption with POC migrating up",
    description: "Long trades with absorption event and POC migrating up - strongest bullish confirmation.",
    kind: "trend-following",
    filters: {
      side: "long",
      event: "confirmed-absorption",
      vpPoc: "poc-migrating-up",
      minInvalidationBps: 2,
      maxInvalidationBps: 5,
      minTradeCount: 250,
      maxTradeCount: 1000,
      maxAbsResultR: 100,
    },
    confirmation: {
      type: "max-favorable",
      thresholdR: 0.25,
    },
  },
  {
    id: "short-absorption-poc-migrate-down",
    label: "Short absorption with POC migrating down",
    description: "Short trades with absorption event and POC migrating down - strongest bearish confirmation.",
    kind: "adverse-reader",
    filters: {
      side: "short",
      event: "confirmed-absorption",
      vpPoc: "poc-migrating-down",
      minInvalidationBps: 2,
      maxInvalidationBps: 5,
      minTradeCount: 250,
      maxTradeCount: 1000,
      maxAbsResultR: 100,
    },
    confirmation: {
      type: "max-favorable",
      thresholdR: 0.25,
    },
  },
  {
    id: "long-tight-inv-2-3-bps",
    label: "Long with tightest invalidation 2-3 bps",
    description: "Long trades with very tight invalidation - only the sharpest entries.",
    kind: "mixed-reader",
    filters: {
      side: "long",
      minInvalidationBps: 2,
      maxInvalidationBps: 3,
      minTradeCount: 250,
      maxTradeCount: 1000,
      maxAbsResultR: 100,
    },
    confirmation: {
      type: "max-favorable",
      thresholdR: 0.25,
    },
  },
  {
    id: "short-tight-inv-2-3-bps",
    label: "Short with tightest invalidation 2-3 bps",
    description: "Short trades with very tight invalidation - only the sharpest entries.",
    kind: "adverse-reader",
    filters: {
      side: "short",
      minInvalidationBps: 2,
      maxInvalidationBps: 3,
      minTradeCount: 250,
      maxTradeCount: 1000,
      maxAbsResultR: 100,
    },
    confirmation: {
      type: "max-favorable",
      thresholdR: 0.25,
    },
  },
];



